import type { NextPage } from "next";
import Head from "next/head";
import { MongoClient } from "mongodb";
import MeetupList from "../components/meetups/MeetupList";

const Home: NextPage = ({ meetups }: any) => {
  return (
    <>
      <Head>
        <title>Next.js Summary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MeetupList meetups={meetups} />
    </>
  );
};

// export async function getServerSideProps(context: any) {
//   const req = context.req
//   const res = context.res

//   //fetch data from an API

//   return {
//     props: {
//       meetups: DUMMY_MEETUPS,
//     }
//   };
// }

export async function getStaticProps() {
  //fetch data from an API
  const client = await MongoClient.connect(
    "mongodb+srv://mrtnprzk:6w1oilWMFg0iMeTt@cluster0.coymc.mongodb.net/nextjs-summary?retryWrites=true&w=majority"
  );
  const db = client.db();

  const meetupsCollection = db.collection("meetups");

  const meetups = await meetupsCollection.find().toArray();

  client.close();

  return {
    props: {
      meetups: meetups.map((meetup) => ({
        id: meetup._id.toString(),
        title: meetup.title,
        address: meetup.address,
        image: meetup.image,
      })),
    },
    revalidate: 10, //revalidating data every 10 sec
  };
}

export default Home;
